Repository sara-nl/SpiderScripts, pull requests merged in 2025-02, with the labels that each got.

#54 Ada: fix --mv error message. Fixes #52
  ada/ada
Labels: bug

#53 Ada: fix --rmlabel --all. Fixes #51
  ada/ada
Labels: bug

#60 Some documentation edits
  README.md
Labels: documentation

#63 Use ada/etc/ada.conf if it exists
  ada/ada
  ada/etc/ada.conf
Labels: enhancement
